Update gridlabd-weather

diff --git a/subcommands/gridlabd-weather b/subcommands/gridlabd-weather
--- a/subcommands/gridlabd-weather
+++ b/subcommands/gridlabd-weather
@@ -36,7 +36,7 @@ function config()
 		echo "CACHEDIR=\"$CACHEDIR\""
 		echo "DATADIR=\"$DATADIR\""
 	elif [ "$1" == "reset" ]; then
-		rm -f $CONFIGFILE || (echo "ERROR: unable to reset $CONFIGFILE" > /dev/stderr; exit 1)
+		rm -f $CONFIGFILE || (echo "ERROR: unable to reset $CONFIGFILE" >> /dev/stderr; exit 1)
 	elif [ "$1" == "set" -a $# == 3 ]; then
 		echo "$2=\"$3\"" >> $CONFIGFILE
 	elif [ "$1" == "get" -a $# == 2 ]; then
@@ -50,7 +50,7 @@ function config()
 		fi
 		echo $value | cut -f2 -d= | cut -f2 -d\"
 	else
-		echo "'$1' is an invalid config option"
+		echo "'$1' is an invalid config option" >> /dev/stderr
 		exit 1
 	fi
 }
@@ -65,19 +65,18 @@ INDEX=$CACHEDIR/$COMMIT_ID
 function fetch_index()
 {
 	if [ ! -d $DATADIR ]; then
-		mkdir -p $DATADIR || (echo "ERROR: unable to create $DATADIR" > /dev/stderr; exit 1)
+		mkdir -p $DATADIR || (echo "ERROR: unable to create $DATADIR" >> /dev/stderr; exit 1)
 	fi
 	if [ ! -d $CACHEDIR ]; then
-		mkdir -p $CACHEDIR || ( echo "ERROR: unable to create $CACHEDIR" > /dev/stderr; exit 1)
+		mkdir -p $CACHEDIR || ( echo "ERROR: unable to create $CACHEDIR" >> /dev/stderr; exit 1)
 	fi
 	if [ ! -f $INDEX -o -z $INDEX ]; then
-		echo -n "Downloading ${GITBRANCH} index of $COUNTRY weather archive from ${GITPROJ}... "
-#		svn $SVNLSOPTIONS ls $GITPROJ/branches/$GITBRANCH/$COUNTRY | grep '.tmy3$' > $INDEX || rm -f $INDEX
+		echo -n "Downloading ${GITBRANCH} index of $COUNTRY weather archive from ${GITPROJ}... " >> /dev/stderr
 		curl -sL $GITHUBUSERCONTENT/$GITUSER/$GITREPO/$GITBRANCH/$COUNTRY/.index >$INDEX
-		echo $(wc -l $INDEX | sed -e 's/ \+/ /g;s/^ //' | cut -f1 -d' ') "weather files found"
+		echo $(wc -l $INDEX | sed -e 's/ \+/ /g;s/^ //' | cut -f1 -d' ') "weather files found" >> /dev/stderr
 	fi
 	if [ ! -f $INDEX ]; then
-		echo "$0: ERROR: unable to fetch index" > /dev/stderr
+		echo "$0: ERROR: unable to fetch index" >> /dev/stderr
 		exit 1
 	fi
 }
@@ -111,7 +110,7 @@ function clean()
 {
 	rm -rf $CACHEDIR 
 	if [ -d $CACHEDIR ]; then
-		echo "$0: ERROR: unable to delete $CACHEDIR" > /dev/stderr
+		echo "$0: ERROR: unable to delete $CACHEDIR" >> /dev/stderr
 		exit 1
 	fi
 	fetch_index
@@ -142,11 +141,8 @@ function get()
 	fetch_index
 	for f in $(index $1); do
 		if [ ! -f $DATADIR/$f ]; then
-			echo -n "Downloading $f... "
-			(curl -sL $GITFILE/$COUNTRY/$f > /tmp/$$ && mv /tmp/$$ $DATADIR/$f && echo "done") || (echo "ERROR: unable to download $f" > /dev/stderr; rm -f /tmp/$$; exit 1)
-		# else
-		# 	echo -n "Refreshing $f... "
-		# 	(curl -sL $GITFILE/$COUNTRY/$f -z $DATADIR/$f > /tmp/$$ && mv /tmp/$$ $DATADIR/$f && echo "done") || (echo "ERROR: unable to refresh $f" > /dev/stderr; rm -f /tmp/$$; exit 1)
+			echo -n "Downloading $f... " >> /dev/stderr
+			(curl -sL $GITFILE/$COUNTRY/$f > /tmp/$$ && mv /tmp/$$ $DATADIR/$f && echo "done") || (echo "ERROR: unable to download $f" >> /dev/stderr; rm -f /tmp/$$; exit 1)
 		fi
 	done
 }
@@ -172,7 +168,7 @@ function delete()
 	fetch_index
 	for f in $(index $1); do
 		if [ -f $DATADIR/$f ]; then
-			rm -f $DATADIR/$f || ( echo "ERROR: unable to delete %f" > /dev/stderr; exit 1)
+			rm -f $DATADIR/$f || ( echo "ERROR: unable to delete %f" >> /dev/stderr; exit 1)
 		fi
 	done
 
@@ -190,5 +186,5 @@ elif [ "$(type -t $1)" = "function" ]; then
 	$*
 	exit 0
 else
-	echo "$0: ERROR: '$1' is not a valid weather command" > /dev/stderr
+	echo "$0: ERROR: '$1' is not a valid weather command" >> /dev/stderr
 fi
